---
title: "Point by point responses to reviewers"

author: "Verónica Cruz-Alonso (ORCID: 0000-0002-0642-036X) ^1,2^ §, 
    Christoph Pucher (ORCID: 0000-0002-9269-1907) ^3^ §, 
    Sophia Ratcliffe (ORCID: 0000-0001-9284-7900) ^4^,
    Paloma Ruiz-Benito (ORCID: 0000-0002-2781-5870) ^2,5^,
    Julen Astigarraga (ORCID: 0000-0001-9520-3713) ^2^,
    Mathias Neumann (ORCID: 0000-0003-2472-943X) ^3^,
    Hubert Hasenauer (ORCID: 0000-0003-3469-4031) ^3^,
    Francisco Rodríguez-Sánchez (ORCID: 0000-0002-7981-1599) ^6,7^"

format: 
  docx: 
    reference-doc: Word_template.docx
bibliography: 
  - references.bib
csl: journal-of-vegetation-science.csl
editor_options: 
  chunk_output_type: console
---

## **Reviewer #1**

This manuscript outlines the development of a new API that will allow users to dynamically work with downscaled climate data that currently sits on an FTP site. This work is very valuable to the scientific modeling community as it provides a more efficient way to work with large amounts of temporally and spatially explicit data.

###### **R1:** We appreciate the positive comment of the reviewer.

My overall recommendation is to accept with very minor revisions. The only real criticism I have is that this paper could utilize more computer science and software developer language. For example, this is clearly an API, but it does not use that term or any typical language to explain its syntax. I would recommend that because this is a software paper, that the authors utilize a little more software development language.

###### **R2:** We have included the API as part of the description of the package (LXX): "As an API (Application Programming Interface), by design, *easyclimate* yields tidy datasets [@wickham_tidy_2014] that facilitate calculation of alternative climatic variables and indices following the [tidyverse](https://www.tidyverse.org/) philosophy. Also, the results of the package *easyclimate* can be used directly or serve as input to calculate climatic indices with other packages, such as ClimInd [@climind] or SPEI [@spei] (see some examples in the vignette [Calculating basic climatic indices with data from easyclimate](https://verughub.github.io/easyclimate/articles/climatic-indices.html)). Furthermore, *easyclimate* might be integrated in other software providing environmental variables (e.g. geodata [@geodata2021])."

## **Reviewer #2**

The work presented by Curz-Alonso et al. is of high quality and usefulness. The authors provide easy access to high resolution climate data on a European scale. The basic function of easyclim is to download a large dataset (1km, daily) in a simple way for researchers who are relatively new to the field of pure climate data processing. The article is clear and concise, with several intuitive examples that allow the reader to understand the scope of the package.\
In this respect, my comments and suggestions are minor, and are detailed below:

###### **R3:** We appreciate the positive feedback of the reviewer.

Introduction

-   L75: Replace "(longitude: -24.5º - 45.25º; latitude: 25.25º - 75.5º;" by "(24.5ºW, 45.25ºE, 25.25ºN, 75.5ºN".

###### **R4:** Done (LXX).

-   L82: The main purpose of the library is to download downscaled climate data. Perhaps some more detail could be given on how the downscaling works, with a schematic figure of this procedure. This will provide more complete information about the data the user is downloading.

###### **R5:** Some more detail on the downscaling procedure as well as a schematic figure (current Figure 2) have been added (LXX).

Why the new versions of the downscaling method do not use EOBS 0.1º?

###### **R6:** Using the finer resolution 0.1° E-OBS data would need some adaptation to the downscaling algorithm. We agree that the aim should be to use the finer resolution E-OBS data for future versions of the downscaled climate data and hopefully will find the resources to adapt the algorithm accordingly.

Functionality

-   L100: Indicate that spatRaster is a Terra class.

###### **R7:** Done (LXX).

Case studies

-   L125: Figure?? please check it.

###### **R8:** Corrected, thanks.

Discussion:

-   L179-183: What is considered a "good internet connection"? Authors should provide objective data on internet connection.

###### **R9:** At least 10 MB/s. According to this report (<https://fairinternetreport.com/research/usa-vs-europe-internet-speed-analysis>), median download speed across Europe is 38 MB/s, with nearly all European countries having \>10 MB/s average download speed. We have included this information in LXX.

## Reviewer #3

This article attempts to show the utility and application of a R package to download high resolution meteorological data in Europe. In general, the presented package is interesting and important, but I have still several comments.

General comments.

The graphical representation could be improved using the full potential of tidyverse, a better projection and a nicer layout. I would add a daily time series plot and it could be of greater interest to show a country or region instead of a bounding box.

###### **R10:** We appreciate the comments of the reviewer. In Figure 1, we have improved the graphical representation by changing the projection to Lambert Azimuthal Equal Area projection, ETRS89 datum, which is the official for Europe. In Figure 3 (previous Figure 2), we provide a ten-days-length daily time series of Wien region, Austria, according to the suggestion.

Minor comments.

L63: Mortality of plants, I guess? Sentence is not really clear.

###### **R11:** We meant mortality of plants (LXX)

L81-: I miss a comment on the validation of the dataset.

###### **R12:** Some information regarding the evaluation and validation of the dataset has been added (LXX).

L100: Add package references for classs SpatRaster (Terra)

###### **R13:** Done (LXX).

L116: If you use the tidyverse grammar, why not using tibble() instead of data.frame()?

###### **R14:** We have changed the example and we have updated the package documentation to make clear that `data.frame` objects created with tibble can be also used as an input.

L128: I would recommend using the sf package to create the geometry, I think the use of sf is more common.

###### **R15:** We have changed how we create Figure 3 and we do not create the vectorial geometry but we download it now (see R10).

L153: I would change the tidyverse pipe %\>% to the R Base \|\>

###### **R16:** Done (LXX).

L159: An easier way is to use lubridate::year(), it is not needed as factor for grouping; if you use pivot_longer() to get a tidier tibble it would make it easy to apply summarise().

###### **R17:** Thanks for the programming suggestions to make the code more efficient. We have included the function lubridate::year() and we have removed as.factor() (LXX). We have not included pivot_longer() since the objective of the example is to show a simple example of how to use the data and variables you can easily get. Using pivot_longer implies to have in the same column values for temperature and precipitation and it can be more confusing.

# References

::: {#refs}
:::
